name: tonic
version: 0.0.2
authors:
- Oliver Steele <steele@osteele.com>
- Rody Davis <rody.davis.jr@gmail.com>
description: >
  Classes and methods for representing and manipulating concepts from music theory:
  Pitch, PitchClass, Interval, Scale, Chord.
homepage: http://github.com/AppleEducate/dart-tonic

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"

dependencies:
  collection: ">=0.9.1 <1.14.11"
  flutter:
    sdk: flutter
    
dev_dependencies:
  # unittest: '>=0.10.0 <0.11.0'
  # test: ^1.3.0
  flutter_test:
    sdk: flutter
